fix(vision/quest): add empty resource/rob_box_quest marker (setup.py data_files)
Build #32900725289 step:25:

  error: can't copy 'resource/rob_box_quest': doesn't exist or not a regular file

setup.py data_files:
  ('share/ament_index/resource_index/packages', ['resource/' + package_name]),
  ('share/' + package_name, ['package.xml']),

Ищет ФАЙЛ resource/<package_name> (не директорию). Образец -
src/rob_box_supervisor/resource/rob_box_supervisor (0 байт).

Fix:
  - создал src/rob_box_quest/resource/rob_box_quest (пустой, 0 байт)
  - Dockerfile: COPY src/rob_box_quest/resource/rob_box_quest /ws/src/.../
  - Убрал RUN mkdir -p resource/ (он делал пустую директорию, не файл)
(cherry picked from commit f73e6eb78775f65f672da09fa12a8a7c46e30801)